comment out fastqc walltime prompt

diff --git a/_run_wgs_qc b/_run_wgs_qc
--- a/_run_wgs_qc
+++ b/_run_wgs_qc
@@ -338,19 +338,19 @@ function review_enriched_seqs() {
 
 
 function run_lane_qc() {
-   while [ 1 ] ; do
-      echo "
-Please enter how long to allow for fastqc - or just press enter to accept default ( $FASTQC_WALL minutes ): 
-"
-      read_answer_with_default $FASTQC_WALL
-      FASTQC_WALL=$answer
-      python -c "print int('$FASTQC_WALL')" >/dev/null 2>&1
-      if [ $? != 0 ]; then
-         echo "error: looks like time requested ( $FASTQC_WALL ) is not a number."
-      else
-         break
-      fi
-   done
+#    while [ 1 ] ; do
+#       echo "
+# Please enter how long to allow for fastqc - or just press enter to accept default ( $FASTQC_WALL minutes ): 
+# "
+#       read_answer_with_default $FASTQC_WALL
+#       FASTQC_WALL=$answer
+#       python -c "print int('$FASTQC_WALL')" >/dev/null 2>&1
+#       if [ $? != 0 ]; then
+#          echo "error: looks like time requested ( $FASTQC_WALL ) is not a number."
+#       else
+#          break
+#       fi
+#    done
 
    echo "
 
